namespace Aufgabe3_RestfulApi.Model {
    public class Author {
        public Author(string name)
        {
            Name = name;
        }

        public int Id { get; private set; } // primary key (autogenerated)
        public string Name { get; set; }
        public Address Contact { get; set; } = null!;

        // Collection navigation property (1:n)
        public List<Post> Posts { get; } = new();
    }

}
