using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aufgabe3_RestfulApi.Model; 
public class Blog {
    public Blog(string name)
    {
        Name = name;
    }

    // [Timestamp] // Optimistic locking
    // public byte[] Version { get; set; } = null!;
    //  public uint Version { get; set; }

    public int Id { get; private set; } // primary key (autogenerated)
    public string Name { get; set; }

    // Collection navigation property:
    // One to many (1:n) relation: Blog -> Post
    // One blog can have many posts, so here we have a one-to-many mapping.
    // n-site, Hibernate @OneToMany 
    public List<Post> Posts { get; } = new();
}
