namespace Aufgabe3_RestfulApi.Model; 
public class Post {
    public Post(string title, string content, DateTime publishedOn)
    {
        Title = title;
        Content = content;
        PublishedOn = publishedOn;
    }

    public int Id { get; private set; } // primary key (autogenerated)
    public string Title { get; set; }
    public string Content { get; set; }
    public DateTime PublishedOn { get; set; }

    // Collection navigation property
    // many to many (n:m) relation: Posts <-> Tags
    public List<Tag> Tags { get; } = new();

    // Navigation property
    // One to many (1:n) relation: Blog -> Post
    // 1-site, Hibernate: @ManyToOne
    // Reference navigation property, Typname Propertyname
    public Blog Blog { get; set; } = null!;

    // Navigation property, Nullable
    public Author? Author { get; set; }
}
