namespace Aufgabe3_RestfulApi.Model; 
public class Tag {
    public Tag(string id, string text)
    {
        Id = id;
        Text = text;
    }

    public string Id { get; private set; }  // primary key (NOT autogenerated)
    public string Text { get; set; }

    // Collection navigation property
    // many to many (n:m) relation: Tags <-> Posts
    public List<Post> Posts { get; } = new();
}
